spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: kkkkk11111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
app:
  security:
    jwt:
      secret: "your-256-bit-secret-key-here-make-it-at-least-32-bytes-long"
